version: '3.3'

services:

 alquiler:
   build:
     context: ./services/alquiler
     dockerfile: Dockerfile-dev
   volumes:
     - './services/alquiler:/usr/src/app'
   ports:
     - 5001:5000
   environment:
     #- FLASK_APP=project/__init__.py
     - FLASK_ENV=development
     - APP_SETTINGS=project.config.DevelopmentConfig
     - DATABASE_URL=postgres://postgres:postgres@alquiler-db:5432/alquiler_dev
     - DATABASE_TEST_URL=postgres://postgres:postgres@alquiler-db:5432/alquiler_test

 alquiler-db:  # nuevo
   build:
     context: ./services/alquiler/project/db
     dockerfile: Dockerfile
   ports:
     - 5435:5432
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres

 nginx:
   build:
     context: ./services/nginx
     dockerfile: Dockerfile-dev
   restart: always
   ports:
     - 80:80
   depends_on:
     - alquiler
